### ISSUE TITLE
readme dosyası

### ISSUE THREAD

**Issue by sedefkilicceken** [sebey11/tensorflow_dataset_olusturmas-1#1]
ReadMe dosyası doldurulsun.

**Comment by sedefkilicceken** [comment]
![screenshot from 2018-12-01 06-43-42](https://user-images.githubusercontent.com/45830441/49906023-2e8c8f00-fe81-11e8-8787-160a88d1ee43.png)

**Comment by sedefkilicceken** [comment]
veri toplama işlemi

**Comment by l3wh3w** [comment]
![image](https://user-images.githubusercontent.com/109236423/179401572-0fdabd75-2942-4b97-8b59-01eb78a32662.png)
Gösterdiğiniz şekilde yaptım ama eğitim aşamasında loss değeri falan çıkmıyor tekrar komut satırı açılıyor. Sorun nereden kaynaklanıyor acaba
